export default Object.freeze({
    FETCH_POSTS:         'FETCH_POSTS',
    FETCH_POSTS_SUCCEED: 'FETCH_POSTS_SUCCEED',
    FETCH_POSTS_FAILED:  'FETCH_POSTS_FAILED',
    
    UPDATE_POSTS:         'UPDATE_POSTS',
    UPDATE_POSTS_SUCCEED: 'UPDATE_POSTS_SUCCEED',
    UPDATE_POSTS_FAILED:  'UPDATE_POSTS_FAILED',

    GET_KEYS: 'GET_KEYS',
    
})