export default Object.freeze({
    FETCH_POSTS:         'FETCH_POSTS',
    FETCH_POSTS_SUCCEED: 'FETCH_POSTS_SUCCEED',
    FETCH_POSTS_FAILED:  'FETCH_POSTS_FAILED',
    
    GET_POSTS:         'GET_POSTS',
    GET_POSTS_SUCCEED: 'GET_POSTS_SUCCEED',
    GET_POSTS_FAILED:  'GET_POSTS_FAILED',

    CHOOSE_DATE: 'CHOOSE_DATE',
    
})